"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const router = useRouter();

  const links = [
    { href: "/details", label: "Property Details" },
    { href: "/location", label: "Location Details" },
    { href: "/f&a", label: "Features & Amenities" },
    { href: "/price", label: "Price Details" },
    { href: "/images", label: "Property Images" },
  ];

  const handleNext = () => {
    const currentIndex = links.findIndex((link) => link.href === pathname);
    const nextIndex = (currentIndex + 1) % links.length;
    router.push(links[nextIndex].href);
  };

  const currentIndex = links.findIndex((link) => link.href === pathname);
  const progressWidth = ((currentIndex + 1) / links.length) * 100;

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <div className="container mx-auto p-4 bg-gray-100 rounded-lg shadow-md">
          <div className="flex flex-row justify-around mb-4 relative">
            {links.map((link) => (
              <Link key={link.href} href={link.href}>
                <h2
                  className={`text-xl font-bold p-2 rounded text-center ${pathname === link.href
                      ? "bg-blue-200 text-gray-700 shadow-md font-bold"
                      : "text-gray-800 font-extralight"
                    }`}
                >
                  {link.label}
                </h2>
              </Link>
            ))}
            <div
              className="absolute bottom-0 left-0 h-1 bg-blue-500 transition-all duration-300"
              style={{ width: `${progressWidth}%` }}
            ></div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-4">{children}</div>
          <div className="flex items-center justify-between bg-[#122B49] text-gray-100 font-medium p-2 rounded-lg mt-6">
            <p className="text-left">
              Need help? Call <span className="font-bold">9999999999</span>
            </p>
            <button
              onClick={handleNext}
              className="bg-[#122B49] border border-white text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            >
              Next
            </button>
          </div>
        </div>
      </body>
    </html>
  );
}
